# lazy-admin-tools: mailserver-generate - client autoconfiguration
# Sourced by mailserver-generate.sh after dkim.sh. Relies on $BASE,
# $OUT already being set, and read_config()/read_domain_config()/
# strip_comments() already defined. Requires tls.sh to have already
# run in this same invocation - it re-derives each domain's
# MX/SMTP/IMAP hostnames and certificate paths rather than reusing
# tls.sh's arrays, but relies on tls.sh having already guaranteed the
# certificate and key exist and match; this file only adds the
# autoconfig-specific SAN check on top. Not standalone executable.
# Produces AUTOCONFIG_BACKEND as a global; writes nginx-autoconfig.conf
# and per-domain autoconfig/<domain>/mail/config-v1.1.xml directly.

# --- Client autoconfiguration (Thunderbird/Outlook): opt-in via the
#     global "autoconfig_backend" config key. Only "nginx" is
#     supported. When enabled, every canonical domain's certificate
#     must also cover its autoconfig hostname (fail-closed, same
#     spirit as the mx/smtp/imap check in tls.sh), and a static
#     autoconfig.<domain>/mail/config-v1.1.xml is generated and served
#     via a generated nginx vhost, using the same mail certificate -
#     no separate certificate lifecycle just for this. Proven manually
#     on two real domains first: a genuine Thunderbird client picked
#     up the generated XML via "settings found at your provider" and
#     connected without any manual server entry. ---
AUTOCONFIG_BACKEND=$(read_config autoconfig_backend)
case "$AUTOCONFIG_BACKEND" in
	""|none|nginx) ;;
	*)
		echo "[ERROR] unknown autoconfig_backend: $AUTOCONFIG_BACKEND (supported: nginx, none)" >&2
		exit 1
		;;
esac

if [[ "$AUTOCONFIG_BACKEND" != nginx ]]; then
	{
		echo "# Generated by mailserver-generate - do not edit, changes will be lost."
		echo "# Autoconfig is disabled (autoconfig_backend is unset or \"none\" in config)."
	} > "$OUT/nginx-autoconfig.conf"
	chmod 644 "$OUT/nginx-autoconfig.conf"
	echo "[OK] generated nginx-autoconfig.conf (disabled)"
	return 0
fi

TLS_CERT_ROOT=/etc/ssl/local
AUTOCONFIG_VHOST_BLOCKS=""
AUTOCONFIG_DOMAIN_COUNT=0
mkdir -p "$OUT/autoconfig"

while read -r domain; do
	MX_HOST=$(read_domain_config "$domain" mx_hostname_pattern | sed "s/%domain%/$domain/")
	SMTP_HOST=$(read_domain_config "$domain" smtp_hostname_pattern | sed "s/%domain%/$domain/")
	IMAP_HOST=$(read_domain_config "$domain" imap_hostname_pattern | sed "s/%domain%/$domain/")
	AUTOCONFIG_HOST=$(read_domain_config "$domain" autoconfig_hostname_pattern | sed "s/%domain%/$domain/")

	if [[ -z "$AUTOCONFIG_HOST" ]]; then
		echo "[ERROR] $domain: autoconfig_hostname_pattern not set - required when autoconfig_backend = nginx" >&2
		exit 1
	fi

	CERT="$TLS_CERT_ROOT/$MX_HOST/cert.pem"
	KEY="$TLS_CERT_ROOT/$MX_HOST/key.pem"

	# tls.sh already guaranteed these exist and the key matches the
	# cert for this MX_HOST - only the additional autoconfig SAN is
	# this file's job to check.
	CERT_SANS=" $(openssl x509 -in "$CERT" -noout -ext subjectAltName 2>/dev/null | grep -o 'DNS:[^,]*' | sed 's/DNS://g' | tr '\n' ' ') "
	if [[ "$CERT_SANS" != *" $AUTOCONFIG_HOST "* ]]; then
		echo "[ERROR] $domain: certificate at $CERT does not cover $AUTOCONFIG_HOST - reissue with cert-add $MX_HOST $SMTP_HOST $IMAP_HOST $AUTOCONFIG_HOST" >&2
		exit 1
	fi

	mkdir -p "$OUT/autoconfig/$domain/mail"
	{
		echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		echo "<clientConfig version=\"1.1\">"
		echo "  <emailProvider id=\"$domain\">"
		echo "    <domain>$domain</domain>"
		echo "    <displayName>$domain</displayName>"
		echo "    <displayShortName>${domain%%.*}</displayShortName>"
		echo ""
		echo "    <incomingServer type=\"imap\">"
		echo "      <hostname>$IMAP_HOST</hostname>"
		echo "      <port>993</port>"
		echo "      <socketType>SSL</socketType>"
		echo "      <authentication>password-cleartext</authentication>"
		echo "      <username>%EMAILADDRESS%</username>"
		echo "    </incomingServer>"
		echo ""
		echo "    <outgoingServer type=\"smtp\">"
		echo "      <hostname>$SMTP_HOST</hostname>"
		echo "      <port>587</port>"
		echo "      <socketType>STARTTLS</socketType>"
		echo "      <authentication>password-cleartext</authentication>"
		echo "      <username>%EMAILADDRESS%</username>"
		echo "    </outgoingServer>"
		echo "  </emailProvider>"
		echo "</clientConfig>"
	} > "$OUT/autoconfig/$domain/mail/config-v1.1.xml"
	chmod 644 "$OUT/autoconfig/$domain/mail/config-v1.1.xml"

	AUTOCONFIG_VHOST_BLOCKS="$AUTOCONFIG_VHOST_BLOCKS
server {
    listen 80;
    listen [::]:80;
    server_name $AUTOCONFIG_HOST;

    location /.well-known/acme-challenge/ {
        root /var/www/acme-challenge;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $AUTOCONFIG_HOST;

    ssl_certificate     $CERT;
    ssl_certificate_key $KEY;

    root /var/www/autoconfig/$domain;

    location /mail/config-v1.1.xml {
        default_type application/xml;
    }

    location / {
        return 404;
    }
}
"
	AUTOCONFIG_DOMAIN_COUNT=$((AUTOCONFIG_DOMAIN_COUNT + 1))
	echo "[OK] $domain: autoconfig prepared ($AUTOCONFIG_HOST)"
done < <(strip_comments "$BASE/domains")

# --- nginx-autoconfig.conf: one file with server blocks for every
#     domain's autoconfig vhost. Not installed automatically to
#     nginx's own sites-enabled by this script - mailserver-deploy
#     owns that, the same as it owns installing
#     rspamd-dkim_signing.conf. ---
{
	echo "# Generated by mailserver-generate - do not edit, changes will be lost."
	echo "# mailserver-deploy installs this to nginx's own sites-available/"
	echo "# (as lazy-admin-tools-autoconfig.conf) when autoconfig_backend ="
	echo "# nginx. Uses each domain's existing mail certificate - no separate"
	echo "# certificate lifecycle just for autoconfig."
	echo "$AUTOCONFIG_VHOST_BLOCKS"
} > "$OUT/nginx-autoconfig.conf"
chmod 644 "$OUT/nginx-autoconfig.conf"
echo "[OK] generated nginx-autoconfig.conf ($AUTOCONFIG_DOMAIN_COUNT domain(s))"
