# lazy-admin-tools: mailserver-generate - DKIM (rspamd sign-only)
# Sourced by mailserver-generate.sh after tls.sh. Relies on $BASE,
# $OUT already being set, and read_config()/read_domain_config()/
# strip_comments() already defined. Not standalone executable.
# Produces DKIM_BACKEND, DKIM_FILTER_DECL, DKIM_FILTER_REF as globals
# for the caller to assemble smtpd-mailtls.conf with.

# --- DKIM (rspamd sign-only): opt-in via the global "dkim_backend"
#     config key. Only "rspamd" is supported - the proven path after
#     a chained opensmtpd-filter-dkimsign setup was tested end-to-end
#     with two real domains and rejected (every filter in an OpenSMTPD
#     chain runs unconditionally, so every domain's filter signed
#     every message regardless of its actual From: domain). See
#     docs/operations.md for the full comparison.
#
#     Fail-closed like the TLS block: every canonical domain must
#     already have a matching, readable DKIM key at the location
#     mail-dkim-create would have put it, before this fragment is
#     generated - no domain silently ends up unsigned because its key
#     was missing, unreadable, or not actually a private key. DKIM
#     keys themselves are managed separately (mail-dkim-create); this
#     only reads what has already been created and refuses to proceed
#     if it is not what mail expects. ---
DKIM_BACKEND=$(read_config dkim_backend)
DKIM_ROOT=/etc/mail/dkim
DKIM_FILTER_DECL=""
DKIM_FILTER_REF=""

case "$DKIM_BACKEND" in
	""|none)
		{
			echo "# Generated by mailserver-generate - do not edit, changes will be lost."
			echo "# DKIM signing is disabled (dkim_backend is unset or \"none\" in config)."
			echo "# See docs/operations.md for how to enable it."
		} > "$OUT/rspamd-dkim_signing.conf"
		chmod 644 "$OUT/rspamd-dkim_signing.conf"
		echo "[OK] generated rspamd-dkim_signing.conf (disabled)"
		;;
	rspamd)
		if ! command -v openssl >/dev/null 2>&1; then
			echo "[ERROR] openssl not found - required to verify DKIM keys" >&2
			exit 1
		fi

		DKIM_DOMAIN_BLOCKS=""
		DKIM_DOMAIN_COUNT=0

		while read -r domain; do
			DKIM_SELECTOR=$(read_domain_config "$domain" dkim_selector)
			if [[ -z "$DKIM_SELECTOR" ]]; then
				echo "[ERROR] $domain: dkim_selector not set (config or domain-overrides) - required when dkim_backend = rspamd" >&2
				exit 1
			fi

			DKIM_KEY="$DKIM_ROOT/$domain.$DKIM_SELECTOR.key"

			if [[ ! -f "$DKIM_KEY" ]]; then
				echo "[ERROR] $domain: DKIM key not found: $DKIM_KEY - run mail-dkim-create $domain first" >&2
				exit 1
			fi
			# Check readability AND validity as the actual consumer
			# (_rspamd), not as root - this script runs as root, so a
			# plain "[[ -r ]]" check only proves root can read it, not
			# that the rspamd process can. Runs openssl as _rspamd via
			# runuser, which fails closed if the group doesn't exist or
			# the key isn't readable to it.
			if ! getent passwd _rspamd >/dev/null 2>&1; then
				echo "[ERROR] $domain: system user _rspamd not found - install rspamd first" >&2
				exit 1
			fi
			if ! runuser -u _rspamd -- openssl pkey -in "$DKIM_KEY" -noout >/dev/null 2>&1; then
				echo "[ERROR] $domain: $DKIM_KEY is not readable by _rspamd, or is not a valid private key" >&2
				exit 1
			fi

			DKIM_DOMAIN_BLOCKS="$DKIM_DOMAIN_BLOCKS
    $domain {
        selector = \"$DKIM_SELECTOR\";
        path = \"$DKIM_KEY\";
    }"
			DKIM_DOMAIN_COUNT=$((DKIM_DOMAIN_COUNT + 1))

			echo "[OK] $domain: DKIM key verified ($DKIM_KEY, selector $DKIM_SELECTOR)"
		done < <(strip_comments "$BASE/domains")

		if [[ "$DKIM_DOMAIN_COUNT" -eq 0 ]]; then
			echo "[ERROR] no canonical domains configured - nothing to generate DKIM signing for" >&2
			exit 1
		fi

		{
			echo "# Generated by mailserver-generate - do not edit, changes will be lost."
			echo "# mailserver-deploy installs this to rspamd's local.d/dkim_signing.conf"
			echo "# automatically when dkim_backend = rspamd (backed up and rolled back"
			echo "# the same way as dovecot-users). This file is not consumed directly"
			echo "# from here - rspamd's own config directory is outside this store."
			echo ""
			echo "use_domain = \"header\";"
			echo "use_redis = false;"
			echo "sign_authenticated = true;"
			echo "sign_local = true;"
			echo ""
			echo "domain {$DKIM_DOMAIN_BLOCKS"
			echo "}"
		} > "$OUT/rspamd-dkim_signing.conf"
		chmod 644 "$OUT/rspamd-dkim_signing.conf"
		echo "[OK] generated rspamd-dkim_signing.conf ($DKIM_DOMAIN_COUNT domain(s))"

		DKIM_FILTER_DECL='filter "rspamd_outgoing" proc-exec "filter-rspamd -settings-id outgoing"
'
		DKIM_FILTER_REF=' filter "rspamd_outgoing"'
		;;
	*)
		echo "[ERROR] unknown dkim_backend: $DKIM_BACKEND (supported: rspamd, none)" >&2
		exit 1
		;;
esac
