# lazy-admin-tools: mailserver-generate - smtpd-mailhosting.conf
# Sourced by mailserver-generate.sh after store.sh (needs its output
# files: smtpd-domains, smtpd-local-recipients, etc.). Relies on
# $BASE, $OUT, $STABLE_GENERATED_PATH already being set, and
# read_config() already defined. Not standalone executable.

# --- smtpd-mailhosting.conf: self-contained fragment; table paths
#     point at $OUT (this run's own directory), not at the stable
#     path, so a staged generation validates its own new data. ---
DOVECOT_LMTP_SOCKET=$(read_config dovecot_lmtp_socket)

if [[ -z "$DOVECOT_LMTP_SOCKET" ]]; then
	echo "[ERROR] dovecot_lmtp_socket not set in $BASE/config" >&2
	exit 1
fi

cat > "$OUT/smtpd-mailhosting.conf" << EOF
# Generated by mailserver-generate - do not edit, changes will be lost.
# The host's own /etc/smtpd.conf should include the STABLE path once:
#   include "$STABLE_GENERATED_PATH/smtpd-mailhosting.conf"
# Requires <aliases> and <localdomains> tables to already be defined
# in the including file.

table smtpd_domains file:$OUT/smtpd-domains
table local_recipients file:$OUT/smtpd-local-recipients
table forward_recipients file:$OUT/smtpd-forward-recipients
table virtual_local file:$OUT/virtual-local
table virtual_forward file:$OUT/virtual-forward

action "system" forward-only alias <aliases>
action "dovecot" lmtp "$DOVECOT_LMTP_SOCKET" rcpt-to virtual <virtual_local>
action "forward" forward-only virtual <virtual_forward>

match for domain <localdomains> action "system"

# 'from any' is required here: a match rule without an explicit
# 'from' defaults to 'from local' (see smtpd.conf(5)), which would
# silently reject all externally submitted mail with
# "550 Invalid recipient". This is not an open relay - rcpt-to is
# still restricted to the known local_recipients/forward_recipients
# tables; only the source restriction is lifted.
match from any for rcpt-to <local_recipients> action "dovecot"
match from any for rcpt-to <forward_recipients> action "forward"
EOF
chmod 644 "$OUT/smtpd-mailhosting.conf"

echo "[OK] generated smtpd-mailhosting.conf"
