#!/bin/bash
# lazy-admin-tools: Generate OpenSMTPD/Dovecot artifacts from /etc/mailserver
# Usage: mailserver-generate [--output DIR]
#
# Reads the declarative store and writes derived artifacts to DIR
# (default: /etc/mailserver/generated/ for standalone/manual use).
# mailserver-deploy calls this with --output pointing at a fresh
# generation directory under /etc/mailserver/generations/, so a
# staged generation is fully self-contained and can be validated in
# full before it is ever promoted to be the live "generated" target.
#
# Does NOT touch /etc/dovecot or /etc/smtpd.conf - that is
# mailserver-deploy's job, after mailserver-validate-generated has
# checked the staged outputs.
#
# Generated files are fully rewritten on every run - they are derived
# artifacts, not source of truth, so no merge/preserve logic applies.
#
# File-backed OpenSMTPD mapping tables use "key value" (whitespace or
# colon separated), not "key = value" - the "=" syntax is only for
# inline tables in smtpd.conf itself.
#
# This script is itself just an orchestrator: each concern lives in
# its own file under lib/mailserver-generate/, sourced in order below.
# They are not standalone executables - they rely on variables and
# functions this script and earlier lib files in the sequence already
# set up (documented at the top of each one). Split out once this
# file passed ~600 lines and stopped being reviewable as one piece;
# the store/generate/validate/deploy pattern of the tool itself
# stayed the same, only the internals of this one step are now
# organized into files small enough to read individually.

set -euo pipefail

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib/mailserver-generate"

# --- Configuration ---
BASE=/etc/mailserver
OUT="$BASE/generated"
STABLE_GENERATED_PATH="$BASE/generated"
# --- End configuration ---

if [[ "${1:-}" == "--output" ]]; then
	if [[ -z "${2:-}" ]]; then
		echo "Usage: mailserver-generate [--output DIR]" >&2
		exit 2
	fi
	OUT="$2"
elif [[ -n "${1:-}" ]]; then
	echo "Usage: mailserver-generate [--output DIR]" >&2
	exit 2
fi

if [[ "$(id -u)" -ne 0 ]]; then
	echo "[ERROR] script must run as root" >&2
	exit 1
fi

for f in domains domain-aliases mailboxes aliases secrets/users config; do
	if [[ ! -f "$BASE/$f" ]]; then
		echo "[ERROR] $BASE/$f not found - run mailserver-init first" >&2
		exit 1
	fi
done

for lib in common store hosting tls dkim autoconfig; do
	if [[ ! -f "$LIB_DIR/$lib.sh" ]]; then
		echo "[ERROR] $LIB_DIR/$lib.sh not found - incomplete installation" >&2
		exit 1
	fi
done

mkdir -p "$OUT"
chmod 700 "$OUT"

# shellcheck source=lib/mailserver-generate/common.sh
source "$LIB_DIR/common.sh"
# shellcheck source=lib/mailserver-generate/store.sh
source "$LIB_DIR/store.sh"
# shellcheck source=lib/mailserver-generate/hosting.sh
source "$LIB_DIR/hosting.sh"
# shellcheck source=lib/mailserver-generate/tls.sh
source "$LIB_DIR/tls.sh"
# shellcheck source=lib/mailserver-generate/dkim.sh
source "$LIB_DIR/dkim.sh"
# shellcheck source=lib/mailserver-generate/autoconfig.sh
source "$LIB_DIR/autoconfig.sh"

# --- smtpd-mailtls.conf: assembled here, not in tls.sh/dkim.sh, since
#     it combines PKI_BLOCKS/PKI_REFS (from tls.sh) with
#     DKIM_FILTER_DECL/DKIM_FILTER_REF (from dkim.sh) into the actual
#     listener lines - the one place both concerns genuinely meet. ---
{
	echo "# Generated by mailserver-generate - do not edit, changes will be lost."
	echo "# The host's own /etc/smtpd.conf should include the STABLE path once:"
	echo "#   include \"$STABLE_GENERATED_PATH/smtpd-mailtls.conf\""
	echo "# Requires <submission_auth> to not already be defined elsewhere in"
	echo "# the including file."
	echo ""
	echo "table submission_auth file:$OUT/smtpd-auth"
	echo "table submission_senders file:$OUT/smtpd-senders"
	echo "$PKI_BLOCKS"
	echo ""
	if [[ -n "$DKIM_FILTER_DECL" ]]; then
		echo "$DKIM_FILTER_DECL"
	fi
	echo "listen on 0.0.0.0 port 25 tls$PKI_REFS"
	echo "listen on ::    port 25 tls$PKI_REFS"
	echo "listen on 0.0.0.0 port 587 tls-require auth <submission_auth> senders <submission_senders>$PKI_REFS$DKIM_FILTER_REF"
	echo "listen on ::    port 587 tls-require auth <submission_auth> senders <submission_senders>$PKI_REFS$DKIM_FILTER_REF"
} > "$OUT/smtpd-mailtls.conf"
chmod 644 "$OUT/smtpd-mailtls.conf"

echo "[OK] generated smtpd-mailtls.conf (${#PKI_NAMES[@]} domain(s), dkim_backend=$([ -z "$DKIM_BACKEND" ] && echo none || echo "$DKIM_BACKEND"))"

echo "[OK] mailserver-generate complete - output in $OUT"
echo ""
echo "-- lazy-admin-tools - dragons@work"
